name: 打包数据包

# 触发条件，使用 workflow_dispatch 允许手动触发
on:
  workflow_dispatch:
    inputs:  # 允许手动触发时输入参数
      artifact_name:
        description: '压缩文件名'
        required: true
        default: 'Mr_Fat_Server_'

jobs:
  download:
    # 指定运行环境，这里使用最新的 macOS
    runs-on: macOS-latest

    steps:
      # 第一步：检出仓库的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：上传 src/DataPacks/Mr.Fat_Server 目录下的所有文件作为 artifact
      - name: Upload files
        uses: actions/upload-artifact@v4
        with:
          name: ${{ github.event.inputs.artifact_name }}  # 自定义 artifact 的名称
          path: src/DataPacks/Mr.Fat_Server/*  # 要上传的文件路径
