name: Download DataPacks

# 触发条件，使用 workflow_dispatch 允许手动触发
on:
  workflow_dispatch:

jobs:
  download:
    # 指定运行环境，这里使用最新的 Ubuntu
    runs-on: ubuntu-latest

    steps:
      # 第一步：检出仓库的代码
      - name: Checkout repository
        uses: actions/checkout@v4

      # 第二步：上传 src/DataPacks/Mr.Fat_Server 目录下的所有文件作为 artifact
      - name: Upload files
        uses: actions/upload-artifact@v3
        with:
          name: Mr_Fat_Server_Files  # Artifact 的名称
          path: src/DataPacks/Mr.Fat_Server/*  # 要上传的文件路径
